### ISSUE TITLE
DUplicate menu not duplicate all parameters.

### ISSUE THREAD

**Issue by dgrabulosa** [Grubuntu/PieMenu#104]
When duplicate a menu the parameters: "icon spacing" and "number of rows" not take the basis workbench proprieties and remain to 0,
and context is not activated (these case I don't know if it is a bug or intentionally remain inactivated).

**Comment by Grubuntu** [comment]
Hi
You are right, it's an oversight, I'll make the change.

Thank you for reporting this.
