### ISSUE TITLE
Increase tools selection capabilities to remove multi selected tools at once.

### ISSUE THREAD

**Issue by dgrabulosa** [Grubuntu/PieMenu#105]
In the tools nice to have the possibility to select multiple tools separated (control key pressed) or all in between first selected and last (shift key pressed) to remove tools easily.

![image](https://github.com/user-attachments/assets/d2e795b6-c3d9-4c50-ac82-099983460910)

**Comment by Grubuntu** [comment]
This feature is now in v1.9.4

Thank you for you support.
