### ISSUE TITLE
FreCad crash pie menu related.

### ISSUE THREAD

**Issue by dgrabulosa** [Grubuntu/PieMenu#106]
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.39141 (Git)
Build type: Release
Branch: main
Hash: 4bd80bdcbb97d6038bc7030aed9ecebf57f4e428
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Spanish/Spain (es_ES)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * FreeCAD-Ribbon 1.3.17.1
  * PieMenu 1.9.2
  * sheetmetal 0.5.3

![image](https://github.com/user-attachments/assets/c9a2a6b0-4c4d-4f2d-afcb-a1bd271ea9a8)

On click exit with green tick.

![image](https://github.com/user-attachments/assets/700fd0ac-4aae-49a7-bee3-0aba8eb13151)

**Comment by Grubuntu** [comment]
thank you for your report.

I will work on this.

**Comment by Grubuntu** [comment]
@dgrabulosa 
I can't reproduce the first error at this moment : can you explain how you get it, please?


I can reproduce the second error: In sketcher when 'Sketcher_Dimension' tool is active and if i close the sketcher with green tick, it creates a violation error. Do you only get this error with the Sketcher_Dimension' tool or in other circumstances?

**Comment by Grubuntu** [comment]
First error is normaly fix with v1.9.3

I'm still working on the second problem.

**Comment by Grubuntu** [comment]
Fixed with v1.9.4
