### ISSUE TITLE
[WIP] [Feature request] Advanced contextual menu triggers

### ISSUE THREAD

**Issue by dgrabulosa** [Grubuntu/PieMenu#118]
Please change the title I cant  ( [Feature request] adnced contextual menu triggers )
I play with contextual menu and the condition to auto trigger.
I miss the possivility to trigger with conditional statemets in between  conditions something like these mokup .
For example if I select two edges it tiggers a menu, if I select one vertex and one edge triggers the same menu or other diferent.....
![image](https://github.com/user-attachments/assets/87086363-5406-4a0f-8b4a-b4c08b77dcbb)

**Comment by Grubuntu** [comment]
It's a good idea, I'm going to think about how to implement it in the code. 

Maybe a formula input box, but that would require syntax checking, or the possibility of adding one or more arrays to create multi-conditions...

**Comment by dgrabulosa** [comment]
Some test button or something that checks the formula befor apply.

**Comment by dgrabulosa** [comment]
Some more things:
when make custom auto trigger pie menu one thing to help determine exact menu trigger are the type of edges, vertex to take in account: normal edges, construction edges, projected edges.

(A crazy idea: parametric or dynamic pie menu: a special menu that the menu tools are configured with conditional statements individually (only one menu configurations that taking in account the selected entities to show the available tools to manipulate these concreted selected entities)  ex: select 2 points only shows the constraint coincident tool with the conditional: points == 2 but not the parallel constraint that have the conditional edges ==2)

**Comment by Grubuntu** [comment]
I've started to work on the possibility of using several conditions, but it's going to take a bit of time.


I'd already thought about a contextual menu but it still seems complicated at the moment, unless we have an internal FreeCAD mapping table that lists all the possible commands depending on the selection, but we don't have that option at the moment. I'll keep this idea aside for later.

**Comment by Grubuntu** [comment]
V1.11 is now available with multi rules context. 

@dgrabulosa try it and tell me what you think about.

Thank you for this great idea !
