### ISSUE TITLE
Pies with command names

### ISSUE THREAD

**Issue by pgilfernandez** [Grubuntu/PieMenu#20]
Very cool your implementation! it looks so promising. The core work is done, I really like it!
I have some comments to make them more robust and prettier:

### Allowance
Now you are allowing them only in circular but the would fit in Rainbow and "left and right" types:
This would be a just icons option:
<img width="262" alt="pie_names_09" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/477c9544-fdc1-44b8-b723-3d53ecbdfa80">

Then you can add names in the outer direction:
<img width="475" alt="pie_names_10" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/02266510-f4ac-4e16-95e0-7aca52ceb499">

This technique also works with Rainbow pies:
<img width="550" alt="pie_names_11" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/0d2a0240-6d59-4698-9f0f-2b94b896facb">

### Items arrangement in circle pies
As the feature is already there (and working so nicely), I would say we just need to work a little bit more in the display/layout maths.
If this is a normal pie with 8 icons:
<img width="225" alt="pie_names_03" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/8a0f7584-0d38-4652-b18d-0d0fdb7813b6">

This is the pie with command names activated:
<img width="428" alt="pie_names_04" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/beb3266f-c94c-40ec-ba1d-9525ed2885ca">

And this is the real example:
<img width="398" alt="pie_names_02" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/f7c6ab24-ef41-4171-972d-f930a39bab0e">

As you see, they get need more spacing between them. In a first approach this would be what I suggest:
1) Vertical spacing so that the names have space to not overlap vertically:
<img width="421" alt="pie_names_05" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/79f558f5-00f1-40b0-91b8-78debc033afc">

2) Then adding some maths to that top and bottom items get nicely aligned:
<img width="433" alt="pie_names_06" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/34ade94c-977c-415a-9a94-a461cbb7a508">

3) at that point you will see that the "circle" arranging gets lost (because of the manual vertical alignment):
<img width="422" alt="pie_names_07" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/ac1fcd00-7be7-482f-8f7c-39ef230e275a">

4) so that we would need to arrange them back in the following way:
<img width="502" alt="pie_names_08" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/ed06f319-5945-41ca-8b5f-2c356ea5cc68">

If you can add maths to that arrangement it would be awesome.

**Comment by pgilfernandez** [comment]
> I would like to let you know that I'm working on command names for LeftRight pie shape, just in case you haven't started working on it ;) this one: <img alt="300193975-02266510-f4ac-4e16-95e0-7aca52ceb499" width="475" src="https://private-user-images.githubusercontent.com/5942369/300902814-775fc40e-cfdf-460b-bfb7-80d5c43ab8fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTYzNzAsIm5iZiI6MTcwNzQ5NjA3MCwicGF0aCI6Ii81OTQyMzY5LzMwMDkwMjgxNC03NzVmYzQwZS1jZmRmLTQ2MGItYmZiNy04MGQ1YzQzYWI4ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMTYyNzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIyM2E5N2NmZjRlMWZjMDcyNmM0ZDcxOWViNTU1ODIwZTQ3ZGFmY2UyY2MxYjRmYzNhMGRjOWZiZDJmM2YzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OZqmE-0rKP0ttQ9kUyfZhf7GbD6l3q5x7F_pIz_L3S0">

This feature has already been merged 7cc7920e0344667239dcbb7099a8588003acd40e
=)

**Comment by Grubuntu** [comment]
I modified the Pie shape with the commands activated for better spacing management:
![Capture d’écran (117)](https://github.com/Grubuntu/PieMenu/assets/56045316/6c205268-2472-4a1b-9b7a-0436192af506)
![Capture d’écran (119)](https://github.com/Grubuntu/PieMenu/assets/56045316/a27b81ed-e097-4a63-93d9-ac30737fb92d)


it's in development version 139 to test: https://github.com/Grubuntu/PieMenu/tree/next-dev139

**Comment by pgilfernandez** [comment]
It looks like we've been working on the same feature in parallel, hehehe.
I feel like my algorithm has a better layout but it still doesn't work properly depending on the number of commands:
<img width="552" alt="pies" src="https://github.com/Grubuntu/PieMenu/assets/5942369/9bd1afac-7d69-44a4-9f73-371894707241">

So, if you don't mind, I'm gonna try to modify your layout to match mine. I have now a spare hour, let's see if it's enough to finish it ;)

**Comment by pgilfernandez** [comment]
I've PR the branch with my proposal for X distribution: https://github.com/Grubuntu/PieMenu/pull/47

Your Y one is different to mine as mine adds a spacing between icons, would you mind to include it as you know better your algorithm than me? I used a spacing of `buttonSize * 1.2` in case you want to use that one.

BTW, our both approaches were pretty similar in concept but your implementation is much better (that's why mine wasn't still working with any number of icons...)

**Comment by Grubuntu** [comment]
Your algorithm is more beautiful than mine. I failed miserably with trigonometry ;)

>  I used a spacing of buttonSize * 1.2 in case you want to use that one.

I fixed minimum Y spacing in this commit : https://github.com/Grubuntu/PieMenu/commit/14f136b20166563c3804c50c2e062d2577583d5a

**Comment by pgilfernandez** [comment]
It looks great! Good team work, hehehe.

Tomorrow or this weekend I would like to fine tune the stylesheets and make the new CommandNames styleable, let me PR it to the new-139 branch, ok?

**Comment by Grubuntu** [comment]
Of course.
