### ISSUE TITLE
Customizable spacing in "table" pies

### ISSUE THREAD

**Issue by pgilfernandez** [Grubuntu/PieMenu#25]
It would be nice that pies based in tables (UpDown, TableUp,...) have a editable parameter to set a spacing among icons. I would add it per pie, that way you can have different pies with different spacings depending on the number of commands, layout, etc...

Thanks!

**Comment by Grubuntu** [comment]
Of course.  You have some good ideas and I couldn't implement them all due to lack of time and skills.
