### ISSUE TITLE
SIGSEGV when creating a new pie

### ISSUE THREAD

**Issue by hasecilu** [Grubuntu/PieMenu#34]
Since I had some parameter from mdkus version I decided to start from zero deleting PieMenu parameters.

Now when I try to create a new menu when switching to it in the GUI to add the commands FreeCAD crashes both when using new menu and copy current menu. In the parameters there is no update on IndexList.

Maybe we would need to enable some kind of console debugging with: `FreeCAD.Console.PrintMessage()`.

Could you try to create a new menu?
Tested on 0.21.2 and 0.22.dev versions.
```
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3e710) [0x7d1c5025c710]
#1  /usr/lib/libQt5Core.so.5(+0x39bcb0) [0x7d1c50b9bcb0]
```

**Comment by Grubuntu** [comment]
No problem noted here on a new installation (new user.cfg file). I tried on 0.21 and 0.22.

Do you have the 3 menus created by default during a new installation?
![Capture d’écran (80)](https://github.com/Grubuntu/PieMenu/assets/56045316/c65d624c-82a5-4314-b8bd-5d361c6a7246)

**Comment by hasecilu** [comment]
Yes, they work fine, only I noted that (maybe because of the crash) values for pie and button sizes resets to default. 

Just when I click on "WBs" the crahs happens.

I'm on Arch Linux
![image](https://github.com/Grubuntu/PieMenu/assets/53124818/de901019-57ff-43c6-8ef4-dd13334df020)

**Comment by Grubuntu** [comment]
Try to write in the parameters via command line to see if it is not a write permission problem:

```
paramPath = "User parameter:BaseApp/PieMenu"
paramGet = App.ParamGet(paramPath)
paramGet.SetString("Test", "Test_Ok")
```

After, check with Tools >Edit parmeters... to check if the string "Test_Ok" was written well
![Capture d’écran (81)](https://github.com/Grubuntu/PieMenu/assets/56045316/d59d96bf-7174-48f4-8716-12de490f9801)

restart Freecad and  check again that the value is still present in the parameters.

**Comment by hasecilu** [comment]
That's not the problem, it appears. In W10 seems to no be problems.
Could be something Linux related or something specific to my system. Maybe if someone could test on other Linux systems. I'll try previous versions.

**Comment by hasecilu** [comment]
Up to 70d58a83 seems to work reliable fine.
Definitiely on 50b8533f there are crashes

**Comment by Grubuntu** [comment]
Try to comment each lines contains and see if it works again:

```
comboShape.addItem(" ") # Add separator
comboShape.model().item(comboShape.count()-1).setEnabled(False)  # Disable the separator 
```
