### ISSUE TITLE
Update `package.xml` file

### ISSUE THREAD

**Issue by hasecilu** [Grubuntu/PieMenu#36]
Now that https://github.com/FreeCAD/FreeCAD-addons/pull/285 was merged the Addon manager redirects to this repo but data is not updated.

![image](https://github.com/Grubuntu/PieMenu/assets/53124818/0ed86497-43d8-4b3a-9a1c-a5d2d1f1f649)

**Comment by Grubuntu** [comment]
It doesn't work, Freecad add a directory "Piemenu-main",  where did I go wrong ?
![Capture d’écran (83)](https://github.com/Grubuntu/PieMenu/assets/56045316/085fa6e3-14f8-465e-882e-be87fb8c67c1)

**Comment by hasecilu** [comment]
Change to `main` branch
`  <url type="repository" branch="main">https://github.com/Grubuntu/PieMenu</url>`

**Comment by Grubuntu** [comment]
Solved : rename the main branch to master and edit the package.xml.
Thank you for your help you put me on the right way.

**Comment by hasecilu** [comment]
It wasn't easier to only edit the xml?

**Comment by Grubuntu** [comment]
It doesn't work with branch name 'main', it seems FreeCad expected a 'master' branch.

**Comment by hasecilu** [comment]
Mmm, I checked it and it's because in this file I didn't include the branch :sweat_smile: .
https://github.com/FreeCAD/FreeCAD-addons/blob/master/.gitmodules
