### ISSUE TITLE
Implementing separator in PieMenus

### ISSUE THREAD

**Issue by Grubuntu** [Grubuntu/PieMenu#59]
As requested in this thread :
https://forum.freecad.org/viewtopic.php?t=84101&start=100#p745928

And as I'd already tried to work on it, and I've finally managed to implement the addition of separators in the menus :

![Capture d’écran (142)](https://github.com/Grubuntu/PieMenu/assets/56045316/9803aec7-e57c-445e-9a36-fa9ce5a0bb41)

![Capture d’écran (143)](https://github.com/Grubuntu/PieMenu/assets/56045316/d62d6da8-fb3d-4ec9-8914-621ddbec3376)

https://github.com/Grubuntu/PieMenu/commit/f222c33297d9c7627d2ea05b0018b617782277cc

I've chosen to make the selectors and associated text (display command name) completely transparent in all styles, but this can be changed.

Can you try it and tell me what you think?

The PieMenuAddSeparator.svg icon could be improved, what do you think @pgilfernandez ?
![PieMenuAddSeparator](https://github.com/Grubuntu/PieMenu/assets/56045316/ef0e2aaf-503b-4322-9c48-88d8185e4770)

Thank you.

**Comment by Grubuntu** [comment]
I found out why it worked for me during my tests: while developing the code, I had created a menu bar that contained the fake 'Separator' command and it worked.

In FreeCAD, if a custom command isn't assigned to a menu bar, PieMenu can't find it...

I'm looking into how to resolve this as best I can.


![Capture d’écran (145)](https://github.com/Grubuntu/PieMenu/assets/56045316/2c974c51-7ca9-431d-b907-910090a6e163)

**Comment by pgilfernandez** [comment]
Umm, I can't even do it manually, "PieMenu" category is not available...

**Comment by Grubuntu** [comment]
I've tried to correct the problem, so you can try again. Thanks for your time.
https://github.com/Grubuntu/PieMenu/commit/1bb631ecee469756b377cf0c1fb3f68b5dd1780b

**Comment by hasecilu** [comment]
Same here, very neat feature!
