### ISSUE TITLE
Creation of Wiki page

### ISSUE THREAD

**Issue by hasecilu** [Grubuntu/PieMenu#63]
I think would be nice to document the features of this addon on the FreeCAD Wiki.

Some days ago I updated the PieMenu entry here: https://wiki.freecad.org/External_workbenches but since there is no Wiki page it redirect to this repo.

As of now I think the content would be the README contents and some documentation done on the forum. I can create the Wiki page but I think you should say how to organize the content of it.

I think it could be possible to create a button (maybe in the bottom-right corner that says "Documentation" and it trigger FreeCAD to open the wiki page (inside FreeCAD), that would be helpful for users.

**Comment by Grubuntu** [comment]
A great idea.

I'll add a button to the documentation and someone can create the wiki page, or I'll do it.
Thanks

**Comment by hasecilu** [comment]
I was thinking on adding:
- Introduction with a picture of a PieMenu
- Installation
- Usage, with the main tabs
- At the end optional: references and links

**Comment by hasecilu** [comment]
This is the initial skeleton, if you have Wiki access you can finish it else you can give the media you prefer to use.
https://wiki.freecad.org/PieMenu_Workbench

**Comment by Grubuntu** [comment]
Thank you very much for your work

I don't have the rights to edit the wiki at the moment (I'll make the request). Feel free to take the initiative of inserting PieMenu screenshots into the wiki that you think are suitable, if you like. PieMenu is a team effort, so you can add your own personal touch.

**Comment by hasecilu** [comment]
I made some progress but there is still missing the context example and the advanced settings.

**Comment by dzid26** [comment]
> I made some progress but there is still missing the context example and the advanced settings.

What does Pie menu has to do with workbenches? I don't see the Pie Workbench. 
![image](https://github.com/Grubuntu/PieMenu/assets/841061/03b4c75d-762d-4e36-a3d8-b94446a4d776)
Maybe it is possible to remove workbench references from the wiki page?

**Comment by hasecilu** [comment]
Maybe, on the Addon Manager it falls under the Workbench group, maybe we need another group like "accesories"

![image](https://github.com/Grubuntu/PieMenu/assets/53124818/320ecb60-c750-4947-a830-2c12e9468afe)

**Comment by hasecilu** [comment]
Can you open the documentation on FreeCAD?
On FreeCAD weekly with Qt5 I got: 

> Could not find QtWebEngineProcess
> /tmp/.mount_freecaltRcxz/AppRun: line 41: 246119 Aborted                 (core dumped) "${MAIN}" "$@"

On FreeCAD with Qt6 PieMenu crashes FreeCAD but of course the documentation can be open in the built-in browser.

Test with:

```python
import Help
>>> Help.show("PieMenu Workbench")
```

**Comment by Grubuntu** [comment]
> Can you open the documentation on FreeCAD? 

It works for me on  39057-conda.

> I think Wiki needs and update prior 1.0 release, I'll update pictures. @Grubuntu let me know if you have pieces of information that want added. Personally I never understand the "context" stuff so I don't know what to put there.

Perhaps an example will speak for itself:


In normal use, the default PieMenu opens when the global shortcut is pressed, but sometimes the user needs specific tools depending on the type of 3D object selected. 

e.g : For example, the user may want only the tools that are useful when a face of a 3D object is selected in PartDesign: 

He can create a PieMenu called 'Faces' containing these tools and set the display conditions for this PieMenu in the Context tab as follows:

![Capture d’écran (253)](https://github.com/user-attachments/assets/abccf259-6e1a-4890-8cb1-2c763e8f6fd8)

If the user selects only one face (while in the PartDesign workbench) and presses the global shortcut,  the ‘Faces’ PieMenu is displayed, giving access only to the tools that the user has set in the ‘Faces’ PieMenu.

![Capture d’écran (252)](https://github.com/user-attachments/assets/5d75abc3-0559-441d-8275-c9e10c535120)


Ticking the box 'Immediate triggering when conditions are met' change the behavior will trigger ticking the box will immediately display the PieMenu without having to press the global shortcut.

**Comment by hasecilu** [comment]
Hey, thanks for the tips, I have added that information to the Wiki page, let me know if there is something that needs to be updated.
