### ISSUE TITLE
v1.5 New features to test

### ISSUE THREAD

**Issue by Grubuntu** [Grubuntu/PieMenu#66]
Hi
@pgilfernandez @hasecilu 

I've published a draft of version 1.5 with a few new features:
https://github.com/Grubuntu/PieMenu/tree/next-release150

- Added support for 'Del' and 'Suppr' keys for deleting Tool in Toollist (Preferences):
press 'Del' or 'Suppr' when a tool is selected in toolist, remove it (as the button "Remove command" do)

- Added validation with 'Enter' and 'Return' keys, when buttons "Validate" and "Cancel" are visible.
(as a side-effect, pressing the Enter and return keys also hides the PieMenu)
![Capture d’écran (154)](https://github.com/Grubuntu/PieMenu/assets/56045316/26f56103-3788-4e92-8525-85bcb421e384)

- Added documentation link (documentation under construction, I don't have the editing rights yet, all help is welcome) https://wiki.freecad.org/PieMenu_Workbench
Is 'Documentation' better than 'Help' ?
![Capture d’écran (153)](https://github.com/Grubuntu/PieMenu/assets/56045316/dfc75471-96e5-45d8-b758-13dc354689d5)

- Added expressions binding in fast spinbox 
![Capture d’écran (154)](https://github.com/Grubuntu/PieMenu/assets/56045316/a4beb7e9-f1d5-4fd4-9430-31affc85eac1)

- Added toggle show/hide PieMenu behavior also for individuals shortcuts: need to change the title slightly
![Capture d’écran (159)](https://github.com/Grubuntu/PieMenu/assets/56045316/61572d02-fb79-4fae-9cee-6a9c82bd644d)

- Added tools shortcuts keys (for each shape !):
![Capture d’écran (153)](https://github.com/Grubuntu/PieMenu/assets/56045316/e1154fcd-3cf0-496c-83b5-2e5fd2b578b4)

![Capture d’écran (155)](https://github.com/Grubuntu/PieMenu/assets/56045316/88fae8b4-adb9-45e6-b048-bd04561cfca8)
![Capture d’écran (157)](https://github.com/Grubuntu/PieMenu/assets/56045316/a468f104-779c-49a4-8b67-f71bcf7ed699)
![Capture d’écran (158)](https://github.com/Grubuntu/PieMenu/assets/56045316/74df7362-a4aa-4cf9-bbe9-329b8880076e)
![Capture d’écran (156)](https://github.com/Grubuntu/PieMenu/assets/56045316/8e5e8f89-965e-40fb-b59a-bf6fca9168d3)

The shortcuts keys are assigned chronologically, starting with the number 0 and incrementing according to the order of the characters in the ASCII table  '0 1 2 3 4 5 6 7 8 9 : ; < = > ? @ A B C etc...' https://www.ascii-code.com/en
It is not possible to customise the shortcuts.

Usage : Simply enable the functionnaly, and press the dedicated shortcut when a PieMenu is open.

EDIT : In this version, Tools shortcuts key are not clickable. I'm going to change that in a future version.

- Updating styles according to the new feature 'Tools shortcut': QLabel#pieMenuShortcut

Try, test and tell me what you think. Thanks.
I hope you will enjoy them.

**Comment by hasecilu** [comment]
Hi, I have tested the new changes and find this:
- `Del` & `Supr` work, would be useful to have something like `Ctrl + Up/Down` to move the selected command? if so, what about to add a separator?
- The behavior with `Enter` and `Return` seems fine to me
- I'll try to make advancement on Wiki today, sent a new PR also
- Super useful to have expression in the spinbox but I noticed that pressing `Enter`/`Return` no longer closes the task panel.
- Toggle works on main PM and when you are in (let's say) PartDesign and the PartDesign menu opens with the default shortcut but in you want the PartDesign in another WB with its custom shortcut it doesn't toggle
- pie-key shortcuts seems to work fine, Does PieMenu have a way to detect if a shortcut conflict with default shortcuts? Personally I use `<` key but is there is someone using letters could be problems or not?

**Comment by Grubuntu** [comment]
Thanks for testing.


> * `Del` & `Supr` work, would be useful to have something like `Ctrl + Up/Down` to move the selected command? if so, what about to add a separator?

Yes, I'm going to think about the possibility of moving the commands around on the keyboard: I'm adding that to my list of things to do.


> * I'll try to make advancement on Wiki today, sent a new PR also

Super !

> * Super useful to have expression in the spinbox but I noticed that pressing `Enter`/`Return` no longer closes the task panel.
 
I'm going to look into it, thanks for pointing it out to me.

> * Toggle works on main PM and when you are in (let's say) PartDesign and the PartDesign menu opens with the default shortcut but in you want the PartDesign in another WB with its custom shortcut it doesn't toggle

Can you explain how to reproduce the problem, I don't see it.

> * pie-key shortcuts seems to work fine, Does PieMenu have a way to detect if a shortcut conflict with default shortcuts? Personally I use `<` key but is there is someone using letters could be problems or not?

No, there is no detection of duplicate shortcuts at this level. I'd thought about limiting the number of shortcuts to just 8 like in Blender... I'll have to do some more tests because I have the impression that some alphabetical shortcuts don't work properly. 
I might have to limit the number of shortcuts to 10 (from 0 to 9).

 I'm still working on it, so please let me know if there are any problems. 

THANKS
Grub

**Comment by hasecilu** [comment]
> Can you explain how to reproduce the problem, I don't see it.

1. Check shortcut toggle 
2. Pressing `<` toggles the default PieMenu
3. Pressing `P,D` activates the PartDesign PieMenu but can't deactivate it. Also note that PD is assigned to be the default on PD WB, so pressing `<` toggles the same as with the default PieMenu.
4. Pressing `S, K` activates the Sketcher PieMenu but can't deactivate it.

Is this the expected behavior?

**Comment by Grubuntu** [comment]
OK, now I understand : Using multiple-key shortcuts causes problems, it's a known limitation for the moment :
https://github.com/Grubuntu/PieMenu/issues/8

it was a bad idea to implement them, only one-key shortcuts or shortcuts with a modifier (CTRL SHIFT ALT) should be used.

**Comment by Grubuntu** [comment]
Thanks to your advice hasecilu, I've corrected a few problems and adjusted a few elements.
I have updated the code:

- Cleaning some redondant code, redefine/factorize some functions (get and set parameter)
- Reorganisation of the code (grouping class, definitions...)
- Added UP and DOWN key for delete and move Tools il toollist (Preferences)
- Added Icon PieMenu to Preference dialog window 
- Fix tools shortcuts keys feature :  shortcut from 0 to 9 and A to Z
- Update stylesheets
- Limits the maximum number of tools in PieMenu to 30 to avoid problems with tools shortcuts (34 or more shortcuts causes unstable behaviour, which I can't explain, so I've deliberately limited to 30 shortcuts)
- Added label and manage toollist (greyed) if maximum number of tool is reached

![Capture d’écran (160)](https://github.com/Grubuntu/PieMenu/assets/56045316/c1fca3cc-9dbc-4477-ae81-4b89d549b813)

![Capture d’écran (161)](https://github.com/Grubuntu/PieMenu/assets/56045316/6a4fcfa7-e769-4de5-a5fc-2c700b6970b7)

**Comment by pgilfernandez** [comment]
Very nice improvements!
I'm not having much time to test or code but they look very cool to me.
I would add the option to hide command shortcuts as once users know the ones that are assigned they may want to hide them while continue using the shortcuts...

**Comment by hasecilu** [comment]
> Cleaning some redondant code, redefine/factorize some functions (get and set parameter)

Do you think that the code would be easier to read/navigate if instead of creating the GUI of the PieMenu settings via code the GUI is created with a `.ui` file with Qt Designer? Translations would not be lost. Also what about moving some classes to other files, is possible? Have you considered to use `pre-commit` to have a formatting hook, this is the one used on main FreeCAD https://github.com/FreeCAD/FreeCAD/blob/main/.pre-commit-config.yaml

> Added UP and DOWN key for delete and move Tools in toollist (Preferences)

Working fine.

> * Added Icon PieMenu to Preference dialog window
> 
> * Fix tools shortcuts keys feature :  shortcut from 0 to 9 and A to T (30 shortcuts)
> 
> * Update stylesheets
> 
> * Limits the maximum number of tools in PieMenu to 30 to avoid problems with tools shortcuts (34 or more shortcuts causes unstable behaviour, which I can't explain, so I've deliberately limited to 30 shortcuts)
> 
> * Added label and manage toollist (greyed) if maximum number of tool is reached

Cool

I made #69

**Comment by Grubuntu** [comment]
> * Do you think that the code would be easier to read/navigate if instead of creating the GUI of the PieMenu settings via code the GUI is created with a `.ui` file with Qt Designer? Translations would not be lost, in case of any change CrowdIn helps yo "remember".

That's probably true, I've never used QtDesigner.

> * Also what about moving some classes to other files, is possible?

Yes, there are ways of improving the readability and maintenance of the code, and I'm taking it one step at a time.

> * Have you considered to use `pre-commit` to have a formatting hook, this is the one used on main FreeCAD https://github.com/FreeCAD/FreeCAD/blob/main/.pre-commit-config.yaml

I have no idea what it is or how to set it up. I'll read the documentation, thanks.

> I did #69

Thanks !

**Comment by Grubuntu** [comment]
>  I would add the option to hide command shortcuts as once users know the ones that are assigned they may want to hide them while continue using the shortcuts...


I added this function in the last release-150 update, thank you for suggesting this idea.

https://github.com/Grubuntu/PieMenu/commit/2f66dac619ce85ee148735b8d01ebe66cc3ed2c1#diff-bde23e3d8118c05e6614f9923e700773a78f6fc9b0fe18ded5fd27cdbec5db7f


I've also modified the Preferences interface so that it follows the FreeCAD graphic codes and a few other adjustments.

![Capture d’écran (170)](https://github.com/Grubuntu/PieMenu/assets/56045316/bb215bfb-e703-4d38-8b0b-2fe43b9d9890)
![Capture d’écran (171)](https://github.com/Grubuntu/PieMenu/assets/56045316/157cddad-3fb8-40a4-8dc8-f1452ed81866)
![Capture d’écran (169)](https://github.com/Grubuntu/PieMenu/assets/56045316/0ae6c8c2-b888-42b2-8cd0-ef2bee7d222a)
![Capture d’écran (168)](https://github.com/Grubuntu/PieMenu/assets/56045316/64adba0a-3f42-4fc1-bc8b-0b27e3428091)

- Matches the style of the Preferences window with the style of FreeCAD Preferences: Groupboxes, Checkboxes left aligned, Spinbox stretched etc
- Added buttons to clear shortcut and globalshortcut
- Highlighting the default PieMenubox by an arrow in front in PieMenu's list and in QuickMenu
- Added checkbox to set the defaut PieMenu in Preferences
- Enable the tools shortcuts will add a column with shortcuts in toollist 
- Added show/hide tools's shortcuts : + spinbox for selected font size
- Removed label and limitation for number of shortcuts in a PieMenu : tools's shortcuts can have all number and letter 0-9 A-Z (except 'X' which bug), beyond 'Z' no shortcuts are allocated.

I'm thinking of freezing the development of this version now.

Feel free to give it a try. Thanks

**Comment by hasecilu** [comment]
Looks good, new changes improve UX, specially marking default menu on dialog.

I'll try to recreate the UI on QtDesigner.
