### ISSUE TITLE
Multi keys not working

### ISSUE THREAD

**Issue by pgilfernandez** [Grubuntu/PieMenu#8]
Trying to create a subpie with the code you shared me I realized that multikeys doesn't work for me.
The pie menu dropdown doesn't work as in your screenshots (mine is lacking the shortcuts):

## Yours
<img width="354" alt="pie" src="https://private-user-images.githubusercontent.com/56045316/297020327-4a65f6da-0247-410c-a27e-99703c6da994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjM3ODEsIm5iZiI6MTcwNTQyMzQ4MSwicGF0aCI6Ii81NjA0NTMxNi8yOTcwMjAzMjctNGE2NWY2ZGEtMDI0Ny00MTBjLWEyN2UtOTk3MDNjNmRhOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE2NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMWVmYzc1OWZmMzI5OTExMTdmN2UxYzI3MTYzY2U4YWY3N2Q3ZmZkYjU1NGIyOWQ1ZjFmNjE2ZjRkZWExOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L1_zc4nfRplLuf0TvEPalOkQ_N2WrNxWLY_AJR32e8k">

## Mine
<img width="354" alt="pie" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/a72ffa1b-90fd-42c7-b3ad-1e6ae606e5cd">

Any idea why?

**Comment by Grubuntu** [comment]
Are the shortcuts correctly saved in the configuration?

Look in FreeCAD > Tools > Edit Parameters
BaseApp > PieMenu > Index

![Capture d’écran (28)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/0a1b823c-3b89-426f-a75e-99ce41099b67)

**Comment by pgilfernandez** [comment]
Yes, they are correctly stored.
When checking it I realized what is the problem: if you have a pie with a single key, for instance "Q", and then create another pie with multikey shortcut and the first one is already taken for a pie with single key, for instance now "Q,A", then it doesn't work as the only pie shown is the one with the single key.

Is that behavior normal?

**Comment by Grubuntu** [comment]
I have the same behavior.

I don't know if this is normal because FreeCAD has a delay mechanism for multikey shortcuts.

![Capture d’écran (29)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/3f6576fa-e2d3-43ff-b61f-bab715572f97)

Pyside should not handle this in the same way.

**Comment by pgilfernandez** [comment]
I understand, that was a possibility and a limitation...
Well, it's not that bad, once you know it's a matter of finding a workaround that works for you, hehehe.

Thanks anyway
