### ISSUE TITLE
In PartDesign and Sketcher workbenches, Pie menu shows error

### ISSUE THREAD

**Issue by raindropsfromsky** [Grubuntu/PieMenu#83]
I have installed Pie Menus in Ondsel 37608 (latest weekly).

In Part Design WB, I created a body and then created a sketch. 
So I was in Sketcher WB, but had not added any sketch yet.
I pressed TAB, and got a pie menu.

But at the same time, I also got this error:

QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'styleContainerWindow'

Worse, the message panel shows a gray panel also (duplicate message). 
![image](https://github.com/Grubuntu/PieMenu/assets/9047168/0077e5c3-2742-47c1-8203-dd1505090790)

Note that the second gray popup shows "(8 times)".
Why 8 times?

I added a sketch and closed the sketch.
So I was in the PD WB at this moment.
I pressed TAB again, and got the same error.

In fact, for every TAB, I am getting the same error, with increasing count numbers.

**Desired:** 
1. There should be no error
2. If there is any error, show only it only once (not in two duplicate forms)
3. The gray error popup shows that multiple errors have occurred. This does not make any sense!

**Comment by Grubuntu** [comment]
Hello,

Thank you for your feedback. 

It's true that this error has been there for some time and I haven't managed to get rid of it yet. I'm going to try and spend as much time as I need to solve the problem.

In the meantime, you can uncheck this box to stop being bothered by the warnings.

![Capture d’écran (224)](https://github.com/Grubuntu/PieMenu/assets/56045316/f30afe42-74fb-41f6-a3c1-ecbd28c9acb4)

**Comment by Grubuntu** [comment]
Don't forget to set up the notification area as you wish:

![Capture d’écran (225)](https://github.com/Grubuntu/PieMenu/assets/56045316/10f4e018-0d51-4b0b-a457-7db64041eb1d)
