### ISSUE TITLE
Choose an FreeCad icon to put in a custom pie menu

### ISSUE THREAD

**Issue by dgrabulosa** [Grubuntu/PieMenu#97]
In the option to change menu icon. The possibility to select
One icon that already shiped with FreeCad.
Good work!!

**Comment by Grubuntu** [comment]
HI

Good idea, I will work on it soon.

**Comment by Grubuntu** [comment]
The latest version v1.9 allows you to choose an icon from the FreeCAD icons. 
Thanks
